account/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required

from account import views

urlpatterns = [
    url(r'^activate/(?P<activation_key>\w+)/$', views.CustomActivationView.as_view(), name='registration_activate'),
    url(r'^register/$', views.CustomRegistrationView.as_view(),
                           name='registration_register'),
    url(r'^logout/$', views.logout_view, name='logout'),
    url(r'^login/$', views.login, name='login'),
    url(r'^$', views.ProfileSettingsView.as_view(), name='profile-settings'),
    url(r'^settings/email/$', views.EmailSettingsView.as_view(), name='email-settings'),
    url(r'^settings/email/verify/(?P<verification_key>\w+)/$', views.EmailVerifyView.as_view(), name='email-verify'),
    url(r'^settings/password/$', views.password_change, name='password-settings'),
    url(r'^require_email/(?P<backend>[^/]+)/$', views.RequireEmailView.as_view(), name='require_email'),
    url(r'^email_sent/$', views.EmailSentView.as_view(), name='email-sent'),
    url(r'delete_association/$', login_required(views.DeleteAssociationView.as_view()), name='delete-association'),
]

project_name/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin

from {{ project_name }} import views

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url('^auth/', include('social.apps.django_app.urls', namespace='social')),
    url(r'^$', views.home, name='home'),
    url('^', include('django.contrib.auth.urls')),
    url(r'^accounts/', include('account.urls', namespace='account')),
    url(r'^accounts/', include('registration.backends.default.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

raccoongang_template/project/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin

from project import views

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url('^auth/', include('social.apps.django_app.urls', namespace='social')),
    url(r'^$', views.home, name='home'),
    url('^', include('django.contrib.auth.urls')),
    url(r'^accounts/', include('account.urls', namespace='account')),
    url(r'^accounts/', include('registration.backends.default.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load staticfiles %}
{% load i18n %}
{% load bower %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>{{ PROJECT_NAME }}</title>

    <!-- Bootstrap -->
    {% block css %}
    <link href="{% static  'bower_components/bootstrap/dist/css/bootstrap.css' %}" rel="stylesheet">
    <link href="{% static  'css/custom.css' %}" rel="stylesheet">
{#    <link href="{% static 'bower_components/select2-4.0.0/dist/css/select2.min.css' %}" rel="stylesheet" />#}
    <link href="{% static 'bower_components/eonasdan-bootstrap-datetimepicker/build/css/bootstrap-datetimepicker.min.css' %}" rel="stylesheet"/>
    <link href="{% static 'bower_components/bootstrap-switch/dist/css/bootstrap3/bootstrap-switch.min.css' %}" rel="stylesheet">
    {% endblock %}

    {% block top_js %}
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    {% endblock %}

  </head>
  <body style="background-color: #dedede;">
    <nav class="navbar-inverse">
      <div class="container">
        <div class="container-fluid">
          <div class="navbar-header">
            <a class="navbar-brand" href="{% url 'home' %}">
      {#        <img alt="Brand" src="...">#}
              {{ PROJECT_NAME }}
            </a>
          </div>

          <div class="navbar-form navbar-right">
            <ul class="nav navbar-nav nav-pills" style="margin: 0 50px 0 0;">
              {% if user.is_authenticated %}
                <li role="presentation" class="dropdown">
                  <a class="dropdown-toggle" data-toggle="dropdown" href="#"
                     role="button" aria-haspopup="true" aria-expanded="false"
                     style="padding:7px 15px 0">
                    <img src="{% static 'images/default_user.jpg' %}" alt="..."
                               class="img-circle" height="22" width="22" style="margin: 0 5px 0 0;">
                    {{ user.full_name }}
                  </a>

                  <ul class="dropdown-menu">
                    <li role="presentation">
                      <a href="{% url 'account:profile-settings' %}" role="button" aria-haspopup="true" aria-expanded="false">
                        {% trans "Profile Settings" %}
                      </a>
                    </li>
                    <li role="presentation">
                      <a href="{% url 'account:logout' %}" role="button" aria-haspopup="true" aria-expanded="false">
                        {% trans "Logout" %}
                      </a>
                    </li>
                  </ul>
                </li>

              {% endif %}
            </ul>

          {% if not user.is_authenticated %}
            <a class="btn btn-primary" href="{% url 'registration_register' %}">{% trans "Sign Up" %}</a>
            <a class="btn btn-success" href="{% url 'account:login' %}?next={{ request.get_full_path }}">
              {% trans "Sign In" %}
            </a>
          {% endif %}
          </div>
        </div>
      </div>
    </nav>
{#                                            Block content#}

    <div class="container custom_container">
    {% include 'account/message.html' %}
      <div class="panel panel-default">
        <div class="panel-body custom_shadow_for_panel-body">
          {% block content %} {% endblock %}
        </div>
      </div>
    </div>

    <footer class="panel-footer">
      <div class="container">
        <p>© Company 2015</p>
      </div>
    </footer>
    {% block js %}
    <script type="text/javascript" src="{% static 'bower_components/jquery/dist/jquery.min.js' %}"></script>
{#    <script type="text/javascript" src="{% static 'bower_components/select2/dist/js/select2.min.js' %}"></script>#}
{#    <script type="text/javascript" src="{% static 'bower_components/select2/dist/js/i18n/ru.js' %}"></script>#}
    <script type="text/javascript" src="{% static 'bower_components/bootstrap-switch/dist/js/bootstrap-switch.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'bower_components/moment/min/moment.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'bower_components/eonasdan-bootstrap-datetimepicker/build/js/bootstrap-datetimepicker.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'bower_components/bootstrap/dist/js/bootstrap.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'bower_components/jquery-validation/dist/jquery.validate.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'bower_components/jquery-form/jquery.form.js' %}"></script>
    {% endblock %}
    {% block extend_script %}{% endblock %}

  </body>
</html>

templates/index.html
{% extends 'base.html' %}
{% block active_home %}class="active"{% endblock %}

{% block content %}
  <div class="jumbotron">
      <div class="container">
        <h1>Hello, world!</h1>
        <p>This is a template for a simple marketing or informational website. It includes a large callout called a jumbotron and three supporting pieces of content. Use it as a starting point to create something more unique.</p>
      </div>
    </div>
{% endblock %}